### ISSUE TITLE
Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down

### ISSUE THREAD

**Issue by codecolony** [alexgkendall/caffe-segnet#57]
Hi Alex,

```
syncedmem.cpp:19] Check failed: error == cudaSuccess (29 vs. 0)  driver shutting down
*** Check failure stack trace: ***
Aborted (core dumped)

```

I get the above error. Any idea what's wrong? I've checked caffe discussions and they all say that it is due to memory issue but GPU memory usage is very low when I run segnet. Strange thing is that I get the segnet output but when the python process is about to exit at the end I get this error. Possibly some clean up code error. I have no clue how to solve it. Any pointers?

**Comment by iglesias** [comment]
This might be a bit too late, but I will share how I solved this issue in case it may help anyone.

I am using the Matlab interface of Caffe. This error would appear when Matlab was shut down after creating a net (in Matlab `caffe.Net(...);`). Debugging the stack trace showed that the error was happening during cleanup. Adding a call to `caffe.reset_all` before closing Matlab solved the issue.

**Comment by codecolony** [comment]
Thanks @iglesias 
This might help me in the future.

**Comment by aditipanda** [comment]
@iglesias Please help. Where shall I add this line "caffe.reset_all"?

It is already there in run_tests.m file, but that function is not called anywhere.

**Comment by iglesias** [comment]
Hi @appyfizzA. According to what I wrote in this thread at the beginning of last year, you can make the call at any moment (after creating a net, of course) :-)

Try doing it directly in the command prompt and see if that helps solving your issue. If it does, then you can it anywhere you would like.

**Comment by aditipanda** [comment]
@iglesias I am using Ubuntu terminal to run programs. The code is written in python programs built on Caffe, that uses Matlab interface. So running "caffe.reset_all" in the terminal is not doing any work. 

I continue to get the same error. I am trying to run this code: https://github.com/BinWang-shu/M2FCN

**Comment by iglesias** [comment]
I was referring to the Matlab command prompt, of course. 

The Python code uses Caffe via its Matlab interface. Hmm. I wonder why it doesn't use Caffe via Python directly, but alas.

I suggest you to dive deeper in the Matlab code (if any), then. Perhaps you are able to find the "Matlab exit point" in your application, and if possible you add the reset_all at the end there.

Good luck!

**Comment by aditipanda** [comment]
Yes, thank you.

**Comment by aditipanda** [comment]
@iglesias 

I was wrong earlier, the code uses Caffe via it's Python interface. Could you please clear one more thing for me? 

In the installation instruction file of the code I am using, it is written "Python and/or MATLAB(optional)". So that means MATLAB is optional. 
Accordingly, I also successfully trained the network on my GPU (Ubuntu, GTX 980 Ti) which does not have MATLAB. 
So does this mean by any chance that this training isn't optimal, as the MATLAB interface could not be used?

Also, while testing, since we are using MATLAB to create a network by the command "caffe.Net(model_name, weights)", that means using MATLAB interface is compulsory for testing. 
But in that case it should also be compulsory for training, as we are using other commands like "caffe.set_gpu(0)". They are also for MATLAB interface. Correct me if I am wrong. 

I am thinking I have to re-train the network after installing MATLAB on my workstation.
